// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'player_performance.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PlayerPerformance _$PlayerPerformanceFromJson(Map<String, dynamic> json) =>
    PlayerPerformance(
      player: json['player'] as String,
      shortName: json['shortName'] as String,
      playerId: (json['playerId'] as num).toInt(),
      birthdate: json['birthdate'] as String,
      team: json['team'] as String,
      teamId: (json['teamId'] as num).toInt(),
      match: json['match'] as String,
      matchId: (json['matchId'] as num).toInt(),
      date: json['date'] as String,
      competition: json['competition'] as String,
      competitionId: (json['competitionId'] as num).toInt(),
      season: json['season'] as String,
      seasonId: (json['seasonId'] as num).toInt(),
      competitionEditionId: (json['competitionEditionId'] as num).toInt(),
      position: json['position'] as String,
      positionGroup: json['positionGroup'] as String,
      minutes: (json['minutes'] as num).toDouble(),
      physicalCheckPassed: json['physicalCheckPassed'] as bool,
      distance: (json['distance'] as num).toDouble(),
      mPerMin: (json['mPerMin'] as num).toDouble(),
      runningDistance: (json['runningDistance'] as num).toDouble(),
      hsrDistance: (json['hsrDistance'] as num).toDouble(),
      hsrCount: (json['hsrCount'] as num).toInt(),
      sprintDistance: (json['sprintDistance'] as num).toDouble(),
      sprintCount: (json['sprintCount'] as num).toInt(),
      hiDistance: (json['hiDistance'] as num).toDouble(),
      hiCount: (json['hiCount'] as num).toInt(),
      psv99: (json['psv99'] as num).toDouble(),
      mediumAccelerationCount: (json['mediumAccelerationCount'] as num).toInt(),
      highAccelerationCount: (json['highAccelerationCount'] as num).toInt(),
      mediumDecelerationCount: (json['mediumDecelerationCount'] as num).toInt(),
      highDecelerationCount: (json['highDecelerationCount'] as num).toInt(),
      explosiveAccelerationToHsrCount:
          (json['explosiveAccelerationToHsrCount'] as num).toInt(),
      timeToHsr: (json['timeToHsr'] as num).toDouble(),
      timeToHsrPostCod: (json['timeToHsrPostCod'] as num).toDouble(),
      explosiveAccelerationToSprintCount:
          (json['explosiveAccelerationToSprintCount'] as num).toInt(),
      timeToSprint: (json['timeToSprint'] as num).toDouble(),
      timeToSprintPostCod: (json['timeToSprintPostCod'] as num).toDouble(),
      changeOfDirectionCount: (json['changeOfDirectionCount'] as num).toInt(),
      timeTo505Around90: (json['timeTo505Around90'] as num).toDouble(),
      timeTo505Around180: (json['timeTo505Around180'] as num).toDouble(),
    );

Map<String, dynamic> _$PlayerPerformanceToJson(
  PlayerPerformance instance,
) => <String, dynamic>{
  'player': instance.player,
  'shortName': instance.shortName,
  'playerId': instance.playerId,
  'birthdate': instance.birthdate,
  'team': instance.team,
  'teamId': instance.teamId,
  'match': instance.match,
  'matchId': instance.matchId,
  'date': instance.date,
  'competition': instance.competition,
  'competitionId': instance.competitionId,
  'season': instance.season,
  'seasonId': instance.seasonId,
  'competitionEditionId': instance.competitionEditionId,
  'position': instance.position,
  'positionGroup': instance.positionGroup,
  'minutes': instance.minutes,
  'physicalCheckPassed': instance.physicalCheckPassed,
  'distance': instance.distance,
  'mPerMin': instance.mPerMin,
  'runningDistance': instance.runningDistance,
  'hsrDistance': instance.hsrDistance,
  'hsrCount': instance.hsrCount,
  'sprintDistance': instance.sprintDistance,
  'sprintCount': instance.sprintCount,
  'hiDistance': instance.hiDistance,
  'hiCount': instance.hiCount,
  'psv99': instance.psv99,
  'mediumAccelerationCount': instance.mediumAccelerationCount,
  'highAccelerationCount': instance.highAccelerationCount,
  'mediumDecelerationCount': instance.mediumDecelerationCount,
  'highDecelerationCount': instance.highDecelerationCount,
  'explosiveAccelerationToHsrCount': instance.explosiveAccelerationToHsrCount,
  'timeToHsr': instance.timeToHsr,
  'timeToHsrPostCod': instance.timeToHsrPostCod,
  'explosiveAccelerationToSprintCount':
      instance.explosiveAccelerationToSprintCount,
  'timeToSprint': instance.timeToSprint,
  'timeToSprintPostCod': instance.timeToSprintPostCod,
  'changeOfDirectionCount': instance.changeOfDirectionCount,
  'timeTo505Around90': instance.timeTo505Around90,
  'timeTo505Around180': instance.timeTo505Around180,
};
